name: Python Application CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cache Pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black isort pytest pytest-cov # Install dev dependencies

      - name: Lint with Flake8
        run: flake8 src tests --count --max-line-length=88 --show-source --statistics

      - name: Check formatting with Black and isort
        run: |
          black --check src tests
          isort --check-only src tests

      - name: Run tests with Pytest and coverage
        run: pytest --cov=src --cov-report=term-missing --cov-report=xml

      - name: Upload coverage to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml
